apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: samurai-app
    component: backend
spec:
  type: ClusterIP           # Internal only — frontend calls backend via backend-service:5000
  selector:
    app: samurai-app
    component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
